'use client'

import './globals.css'
import { RecoilRoot } from 'recoil'
import type { Metadata } from 'next'
import Link from 'next/link'
import Image from 'next/image'
import { Inter } from 'next/font/google'

// import { UseInkProvider } from 'useink'
// import { AlephTestnet, ShibuyaTestnet } from 'useink/chains'

import { useEffect, useState } from 'react'
import { Dialog } from '@headlessui/react'
import dynamic from 'next/dynamic'

import { Bars3Icon, BellIcon, XMarkIcon } from '@heroicons/react/24/outline'

import { Notification } from '@/layouts/Notification'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const AccountLogin = dynamic(() => import('@/layouts/AccountLogin'), {ssr: false})

const navigation = [
  { name: 'PixelLand', href: '/', current: true },
  { name: 'Lottery', href: '/lottery', current: false },
  { name: 'Adventures', href: '/adventures', current: false },
  { name: 'Shooter', href: '/shooter', current: false },
]

function classNames(...classes: string[]) {
  return classes.filter(Boolean).join(' ')
}

export default function Example({ children }: { children: React.ReactNode }) {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)

  return (
    <html lang="en" className="h-full">
      <body className={classNames(inter.className, 'h-full bg-white')}>
        {/*
        This example requires updating your template:

        ```
        <html class="h-full bg-gray-100">
        <body class="h-full">
        ```
      */}
        {/* <UseInkProvider 
          config={{ 
            dappName: 'Pixelland', 
            chains: [AlephTestnet],
          }}
        > */}
        <RecoilRoot>
          <div className="bg-white">
            <header className="absolute inset-x-0 top-0 z-50">
              <nav className="flex items-center justify-between p-2 lg:px-8" aria-label="Global">
                <div className="flex lg:flex-1">
                  <a href="#" className="-m-1.5 p-1.5">
                    <span className="sr-only">Your Company</span>
                    <Image
                      className="h-12 w-auto"
                      // src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600"
                      src="/images/pixel_logo.png"
                      width={46}
                      height={48}
                      alt=""
                    />
                  </a>
                </div>
                <div className="flex lg:hidden">
                  <button
                    type="button"
                    className="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700"
                    onClick={() => setMobileMenuOpen(true)}
                  >
                    <span className="sr-only">Open main menu</span>
                    <Bars3Icon className="h-6 w-6" aria-hidden="true" />
                  </button>
                </div>
                <div className="hidden lg:flex lg:gap-x-12">
                  {navigation.map((item) => (
                    <Link key={item.name} href={item.href} className="text-md font-semibold leading-6 text-gray-800">
                      {item.name}
                    </Link>
                  ))}
                  {/* <Link href='/mintupload' className="text-sm font-semibold leading-6 text-gray-900">
                    MintUpload
                  </Link> */}
                </div>
                <div className="hidden lg:flex lg:flex-1 lg:justify-end">
                  <AccountLogin />
                </div>
              </nav>
              <Dialog as="div" className="lg:hidden" open={mobileMenuOpen} onClose={setMobileMenuOpen}>
                <div className="fixed inset-0 z-50" />
                <Dialog.Panel className="fixed inset-y-0 right-0 z-50 w-full overflow-y-auto bg-white px-6 py-6 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10">
                  <div className="flex items-center justify-between">
                    <a href="#" className="-m-1.5 p-1.5">
                      <span className="sr-only">Pixelland</span>
                      <Image
                        className="h-8 w-auto"
                        // src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600"
                        src="/images/pixel_logo.png"
                        width={30}
                        height={32}
                        alt=""
                      />
                    </a>
                    <button
                      type="button"
                      className="-m-2.5 rounded-md p-2.5 text-gray-700"
                      onClick={() => setMobileMenuOpen(false)}
                    >
                      <span className="sr-only">Close menu</span>
                      <XMarkIcon className="h-6 w-6" aria-hidden="true" />
                    </button>
                  </div>
                  <div className="mt-6 flow-root">
                    <div className="-my-6 divide-y divide-gray-500/10">
                      <div className="space-y-2 py-6">
                        {navigation.map((item) => (
                          <Link
                            key={item.name}
                            href={item.href}
                            className="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50"
                            onClick={() => setMobileMenuOpen(false)}
                          >
                            {item.name}
                          </Link>
                        ))}
                      </div>
                      <div className="py-6">
                        <a
                          href="#"
                          className="-mx-3 block rounded-lg px-3 py-2.5 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50"
                        >
                          Log in
                        </a>
                      </div>
                    </div>
                  </div>
                </Dialog.Panel>
              </Dialog>
            </header>

            <div className="relative isolate px-6 pt-12 lg:px-8">
              <div
                className="absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80"
                aria-hidden="true"
              >
                <div
                  className="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]"
                  style={{
                    clipPath:
                      'polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)',
                  }}
                />
              </div>
              <div className="py-4 flex flex-col items-center">
                {children}
              </div>
              <div
                className="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-41rem)]"
                aria-hidden="true"
              >
                <div
                  className="relative left-[calc(50%+3rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%+36rem)] sm:w-[72.1875rem]"
                  style={{
                    clipPath:
                      'polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)',
                  }}
                />
              </div>
            </div>
            <Notification />
          </div>
        </RecoilRoot>
        {/* </UseInkProvider> */}
      </body>
    </html>
  )
}

