// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { BeastAction } from './beast-action.js';


export class UpdateState {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UpdateState {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUpdateState(bb:flatbuffers.ByteBuffer, obj?:UpdateState):UpdateState {
  return (obj || new UpdateState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUpdateState(bb:flatbuffers.ByteBuffer, obj?:UpdateState):UpdateState {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UpdateState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

beastMoves(index: number, obj?:BeastAction):BeastAction|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new BeastAction()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

beastMovesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

beastShoots(index: number, obj?:BeastAction):BeastAction|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new BeastAction()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

beastShootsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

beastDeaths(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

beastDeathsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

beastDeathsArray():Int32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Int32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startUpdateState(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addBeastMoves(builder:flatbuffers.Builder, beastMovesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, beastMovesOffset, 0);
}

static startBeastMovesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static addBeastShoots(builder:flatbuffers.Builder, beastShootsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, beastShootsOffset, 0);
}

static startBeastShootsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static addBeastDeaths(builder:flatbuffers.Builder, beastDeathsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, beastDeathsOffset, 0);
}

static createBeastDeathsVector(builder:flatbuffers.Builder, data:number[]|Int32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createBeastDeathsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createBeastDeathsVector(builder:flatbuffers.Builder, data:number[]|Int32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startBeastDeathsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endUpdateState(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishUpdateStateBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedUpdateStateBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createUpdateState(builder:flatbuffers.Builder, beastMovesOffset:flatbuffers.Offset, beastShootsOffset:flatbuffers.Offset, beastDeathsOffset:flatbuffers.Offset):flatbuffers.Offset {
  UpdateState.startUpdateState(builder);
  UpdateState.addBeastMoves(builder, beastMovesOffset);
  UpdateState.addBeastShoots(builder, beastShootsOffset);
  UpdateState.addBeastDeaths(builder, beastDeathsOffset);
  return UpdateState.endUpdateState(builder);
}
}
