// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class CharacterAttrsFbs {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CharacterAttrsFbs {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

hp():number {
  return this.bb!.readUint8(this.bb_pos);
}

angle():number {
  return this.bb!.readInt16(this.bb_pos + 2);
}

weapon():number {
  return this.bb!.readUint8(this.bb_pos + 4);
}

x():number {
  return this.bb!.readInt16(this.bb_pos + 6);
}

y():number {
  return this.bb!.readInt16(this.bb_pos + 8);
}

static sizeOf():number {
  return 10;
}

static createCharacterAttrsFbs(builder:flatbuffers.Builder, hp: number, angle: number, weapon: number, x: number, y: number):flatbuffers.Offset {
  builder.prep(2, 10);
  builder.writeInt16(y);
  builder.writeInt16(x);
  builder.pad(1);
  builder.writeInt8(weapon);
  builder.writeInt16(angle);
  builder.pad(1);
  builder.writeInt8(hp);
  return builder.offset();
}

}
