// automatically generated by the FlatBuffers compiler, do not modify

// export { CharacterAttrsFbs } from './character-attrs-fbs'
// export { PixelShooterUpdatesFbs } from './pixel-shooter-updates-fbs'

export * from './encode'